### ISSUE TITLE
`TypeError: files.flat is not a function` with v0.31.0 on Node 10

### ISSUE THREAD

**Issue by SimonAlling** [igorshubovych/markdownlint-cli#258]
Our CI pipeline suddenly started failing with this error:

```
/usr/local/lib/node_modules/markdownlint-cli/markdownlint.js:107
  return files.flat().map(file => ({
               ^

TypeError: files.flat is not a function
    at prepareFileList (/usr/local/lib/node_modules/markdownlint-cli/markdownlint.js:107:16)
```

We do `npm install -g markdownlint-cli`, meaning we always get the latest version. v0.30.0 was fine, but v0.31.0 (released 2 days ago) fails. `Array.prototype.flat` was introduced in 2ea8a2c8fde26ad0def11856fd1b14923f81ab8b, which was included in the v0.31.0 release.

While writing this issue, I realized markdownlint-cli can't really be blamed for this, since we're using Node 10, which is EOL. I decided to keep the issue anyway for reference, in case anyone else runs into this problem.

**Comment by SimonAlling** [comment]
Solution: Use [a Node version with `Array.prototype.flat` support](https://node.green).

**Comment by chgans** [comment]
v0.32.1 has still that issue. I've downgraded to v0.30.0

What's interesting is that when run in a repo with `pre-commit` that install it's own node version using nodeenv/virtualenv, the problem does not show up (I thought that `pre-commit` was running the checks in a jail).

Running the same config in a repo that doesn't have it's own node version, the "bug" shows up.

**Comment by DavidAnson** [comment]
Per above, this happens when using an old, unsupported version of Node. Version 0.32.1 of this project declares a minimum allowed Node version of 14.

**Comment by chgans** [comment]
I get that, but why the right version of node is not installed automatically?
Could this package at least error out with "your version of node.js" is not supported?
I'm using LTS version of node and it took me quite some time to find out what the problem was.

From https://pre-commit.com/hooks.html, I followed this: https://github.com/igorshubovych/markdownlint-cli#use-with-pre-commit

Nowhere there is mention of minimum node version.

**Comment by nschonni** [comment]
> I'm using LTS version of node and it took me quite some time to find out what the problem was.

Node 10 was an LTS release, but has been end of life for more than year https://github.com/nodejs/Release#end-of-life-releases so I would expect a lot of your packages are going to be failing as most have dropped support as they become EOL

**Comment by chgans** [comment]
I don't understand what's going on, Current LTS is v16 as per https://github.com/nodejs/Release#release-schedule

**Comment by chgans** [comment]
but you are right:
```
$ node --version
v10.19.0
$ which node
/usr/bin/node
```

So the problem is maybe at integration level with the pre-commit tool, this:
https://github.com/igorshubovych/markdownlint-cli/blob/master/package.json#L9-L10
 doesn't seem to have any influence when i use markdownlint with pre-commit:
```
  - repo: https://github.com/igorshubovych/markdownlint-cli
    # Latest is v0.32.1, but has an issue:
    # See https://github.com/igorshubovych/markdownlint-cli/issues/258
    rev: v0.30.0
    hooks:
      - id: markdownlint
        files: \.md$
        args: [--fix]
```

It looks like this can be fixed with:
```
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.1
    hooks:
      - id: markdownlint
        files: \.md$
        args: [--fix]
        language_version: lts <---------------------
```

Might be worse mentioning the minimun node version in the README?

**Comment by DavidAnson** [comment]
I tried to fix this problem with precommit, but that team very explicitly said not to: https://github.com/igorshubovych/markdownlint-cli/issues/157

Supported versions of the Node runtime are declared by this package in the usual manner: https://github.com/DavidAnson/markdownlint/blob/2488a5c0ce92d65ddcc6422f5d453384f3c1e1be/package.json#L53

**Comment by DavidAnson** [comment]
All supported versions of Node are supported and tested in CI: https://nodejs.org/en/about/releases/
